### ISSUE TITLE
Base Price

### ISSUE THREAD

**Issue by heberholanda** [shudnal/TradersExtended#1]
I tried this setting to overwrite the values, but it didn't work.

**shudnal.TradersExtended.haldor.buy.json**

`[

  {	"prefab": "HelmetYule", 	"stack": 1,	"price": 200,	"requiredGlobalKey": ""	},
  {	"prefab": "HelmetDverger", 	"stack": 1,	"price": 1240,	"requiredGlobalKey": ""	},
  {	"prefab": "BeltStrength", 	"stack": 1,	"price": 1900,	"requiredGlobalKey": ""	},
  {	"prefab": "YmirRemains", 	"stack": 1,	"price": 240,	"requiredGlobalKey": ""	},

]`

**Comment by shudnal** [comment]
Thanks. Fixed in 1.0.8
