### ISSUE TITLE
Setkey defeated_eikthyr error after update

### ISSUE THREAD

**Issue by literallygoblin** [shudnal/TradersExtended#10]
![Screenshot 2024-07-17 141528](https://github.com/user-attachments/assets/f44bdfc4-d713-4548-93a0-d3e2905f9543)
![Screenshot 2024-07-17 141757](https://github.com/user-attachments/assets/e71be528-1005-48f0-b005-3586b94a10eb)

This error message and the Cool Shield™ is suddenly showing up when the defeated_eikthyr key is set after the latest updates. All other keys appear to be functioning normally in accordance with the buy/sell JSONs and the issue persists with only this mod in the load order.

**Comment by literallygoblin** [comment]
You got it, boss. I'm adding the buy lists too, just in case.

[shudnal.TradersExtended.hildir.buy.json](https://github.com/user-attachments/files/16268070/shudnal.TradersExtended.hildir.buy.json)
[shudnal.TradersExtended.common.sell.json](https://github.com/user-attachments/files/16268067/shudnal.TradersExtended.common.sell.json)
[shudnal.TradersExtended.haldor.buy.json](https://github.com/user-attachments/files/16268068/shudnal.TradersExtended.haldor.buy.json)
[shudnal.TradersExtended.haldor.sell.json](https://github.com/user-attachments/files/16268069/shudnal.TradersExtended.haldor.sell.json)

**Comment by literallygoblin** [comment]
![Screenshot 2024-07-17 173742](https://github.com/user-attachments/assets/3694998b-0bd7-4c49-8b9b-56e115a321d3)
I'll also add that the shield cannot be bought. It just displays this.

**Comment by shudnal** [comment]
The shield is just placeholder for item capsule.

**Comment by shudnal** [comment]
I still can't reproduce. I need you config file shudnal.TradersExtended.cfg
I see you disabled traders coins, maybe something else is changed that can cause it.

**Comment by literallygoblin** [comment]
[shudnal.TradersExtended.zip](https://github.com/user-attachments/files/16269237/shudnal.TradersExtended.zip)

**Comment by shudnal** [comment]
What global keys are set? Make a screenshot of listkeys command pls.

**Comment by shudnal** [comment]
Ah I get it. You have added the wrong prefab Eikthyr_antler. It's prefab for Eikthyr attack animation.

**Comment by shudnal** [comment]
Anyway I will add protection from that in the next version,

**Comment by shudnal** [comment]
No problem. Situation like this only makes mod more stable and protected from errors.

**Comment by literallygoblin** [comment]
On another note, is the implementation of private keys on the agenda? I can think of a situation or two were it would be nice to be able to lock certain items (like boss items) behind private instead of global keys and have been wanting to ask you about it.

**Comment by shudnal** [comment]
What private key you thought you could set? Some unique ones similar to global?

**Comment by literallygoblin** [comment]
Yeah, the player keys that govern player-based raids.
If the traders' inventories can be tied to the global keys, surely they can also be tied to the player keys? It would be pretty useful on servers were players have different progress.

**Comment by shudnal** [comment]
Idea is fine and job is done. Thanks!
