### ISSUE TITLE
What is the current state of custom buy/sell json?

### ISSUE THREAD

**Issue by BETLOG** [shudnal/TradersExtended#11]
Has anybody done or seen any properly fleshed out buy/sell lists?
I have collated those found/linked in https://github.com/shudnal/TradersExtended/issues/5 and https://github.com/shudnal/TradersExtended/issues/7, but there are a lot of places where the prices are obviously placeholders.

Does a well developed, fully priced, list exist anywhere?
Has anybody discussed what a dragon tear, or pine seed is really, objectively worth? I know there are those who think about this stuff a lot more than I do. We need a price list.

Here's what I've copied and pasted from the various sources.
[shudnal.TradersExtended.zip](https://github.com/user-attachments/files/17570342/shudnal.TradersExtended.zip)

**Comment by shudnal** [comment]
I am not aware of any post Ashlands properly aligned items list with balanced prices.
And github Issues doesn't look as a crowded place to ask for an assistance. 
You can search comments at Nexus there were a couple of links to other mod profiles with item lists.

**Comment by BETLOG** [comment]
Yeah, I was kind of hoping a) you would know b) it would be the place most likely to be found for anyone else searching this same topic in future.

I just realised that a tab i had opened got overlooked, so i only just saw this set:
https://www.nexusmods.com/valheim/mods/2564
It has a good quantity of basic items with what at first glance seems to be well-considered prices, but it lacks seeds, and possibly other such 'auxiliary' things. Still; its a pretty good start.

BTW: are those filenames the only possibilities? or will the mod also parse names like: `shudnal.TradersExtended.common.buy_betlogWants.json` etc

**Comment by shudnal** [comment]
Yes file names are strict. Why do you need other names? You can group them in folders if you want files with the same name.

**Comment by BETLOG** [comment]
> You can group them in folders if you want files with the same name.

Please tell me if i understand this correctly:
-are subdirectory names strict? if so how?
- all json in subdirectories are parsed?
- all parsed files are aggregated at the trader gui?
- item duplication appears multiple times?

>why

i dont know what i want, i'm feeling my way around how it all works, so its nice to know the basic parameters.

**Comment by shudnal** [comment]
Every file in `...\BepInEx\config\shudnal.TradersExtended` will be checked and if its name is match "shudnal.TradersExtended.{trader name}.{buy/sell}.json" it will be parsed.
All files will be combined.
Duplicate items will not be added if it is full duplicate in all fields. You can add the same item name with different stacks, prices, quality, global keys.
If you want to temporary exclude file from loading you can break trader name like changing `shudnal.TradersExtended.haldor.buy.json` to `shudnal.TradersExtended.haldor1.buy.json`
