### ISSUE TITLE
Coins with vendors

### ISSUE THREAD

**Issue by Simoss22** [shudnal/TradersExtended#12]
I don't know if it's since the new patch but the vendors all have the same bank of coins. if Haldor is at 0 coins all the sellers are at 0 coins too
In my memory, each trader had his own money

Thank you.

Simoss
ValheimPvpQc

**Comment by shudnal** [comment]
Thanks! I'll check for that.

**Comment by shudnal** [comment]
![image](https://github.com/user-attachments/assets/fbce5620-2f6c-4f4a-80b3-84a6f6b14c5c)
It worked as intended. Current trader coins limit is 10000. After sleep coins were updated accordingly.
I even spent some money at different traders to see if spent money somehow shared between them.
If you have more info on the issue it needs reproduction steps.
The code responsible for coins update is pretty simple and I can't see even potential issue or any compatibility problem.
