### ISSUE TITLE
Unable to Sell with Controller

### ISSUE THREAD

**Issue by stevengdev** [shudnal/TradersExtended#2]
This mod is fantastic, but I noticed that while I can still scroll the buy window and make purchases, I'm unable to tab over to the sell window in order to sell items via controller.

**Comment by shudnal** [comment]
I'll see what I can do for it. But can't promise anything as I have no controller to test it.

**Comment by shudnal** [comment]
Made it at 1.0.17.
Scroll list using right stick. Sell item using (X). Ignore button hint.
