### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Bumbletr0n** [shudnal/TradersExtended#3]
Not working

**Comment by Bumbletr0n** [comment]
I don't know where to make suggestions, but it would be neat if spending money in the EpicLoot window also applied to Haldor's marketprice fluctuation. 
Thanks for the changes!

**Comment by shudnal** [comment]
Do price change working for you? If not then it's some mod adding traders items incorrectly.

**Comment by Bumbletr0n** [comment]
The price change is working for me, yes. 

When I type something into the search bar like "arr", the arrows don't show up. Even when I try to be more specific like "Resin". 
And if I hit Enter to try to do a search, it just opens the chat box.

**Comment by Bumbletr0n** [comment]
![image](https://github.com/shudnal/TradersExtended/assets/134341663/5c4231bf-f90f-481e-b1c0-77895aa04f58)
The search bar works from the selling column but not the buying column

**Comment by shudnal** [comment]
It's definitely some other mod.

**Comment by shudnal** [comment]
ALso I didn't see price change on the screenshot. Did you enable it to check and then disabled?

**Comment by Bumbletr0n** [comment]
I had disabled the price fluctuation. 
I also disabled the trader coins and it shows my items as greyed out, BUT I'm still able to sell them. Minor bug. 
![image](https://github.com/shudnal/TradersExtended/assets/134341663/cd732900-a96a-40ab-b94d-36aa9eea85f6)

**Comment by shudnal** [comment]
Thanks greyed items was fixed.
If you enable price changing do it work or not? Do price change in the buy list?
Do you have errors in log?
Do you have another mod adding items for trader to sell?
Do you have similar issue with Hildir?

**Comment by Bumbletr0n** [comment]
I removed all my mods except for ExtendedTraders and both search bars work again. 
I'll try to narrow down which one's causing the issue. Sorry about that. 
I'm not getting any red text whatsoever. 

Here is my list of mods. Do you have any suspicions?
Almanac 3.2.0
Armory 1.1.8
AutoDoors 1.0.0
AzuAntiArthriticCrafting 1.3.4
AzuAreaRepair 1.1.3
AzuExtendedPlayerInventory 1.3.12
Backpacks 1.3.3
BalrondElvenRoof 1.0.1
BalrondHumanoidRandomizer 1.2.3
BalrondShipyard 1.3.6
BetterWisps 1.0.26
BowsBeforeHoes 1.3.4
BuildCameraCHE 1.2.2
BuildRestrictionTweaksSync 1.0.2
ClockMod 1.6.0
ComfortTweaks 3.2.10
ConfigurationManager 18.2
CookingAdditions 1.0.9
CraftFromContainers 3.5.1
CreatureLevel&LootControl 4.5.19
CustomRaids 1.7.10
DeathPinRemoval 1.0.4
Digitalroot'sBounties 3.0.9
Digitalroot'sSlopeCombatAssistance 2.0.22
DisplayBepInExInfoIn-Game 2.0.2
DragoonCapes 1.2.8
DropThat! 2.3.11
EpicLoot 0.9.37
EpicMMOSystem 1.8.97
FirstPersonMode 1.3.2
FishChum 1.0.1
FogPushers 1.0.2
ForsakenPowerOverhaul 1.1.4
FortifySkillsRedux 1.0.8
GreydwarfsDontCircle 1.0.0
Groups 1.2.6
HoneyPlus 5.3.2
InstantMonsterDrop 0.5.0
Jotunn 2.18.0
kg.moremappins 1.0.0
LootParticlePlus 1.1.0
MagicPlugin 1.8.9
MassFarming 1.9
MissingPieces 2.0.7
MonsterLabZ 3.0.7
Monstrum 1.3.5
MonstrumAshlands 1.1.6
MonstrumDeepNorth 1.1.7
MultiUserChest 0.5.10
NeedForSpeed 0.2.1
Network 1.0.2
OdinArchitect 1.2.7
Outsiders 1.5.5
ParticleControl 0.0.2
Pathfinder 2.0.11.0
PerfectPlacement 1.1.6
PlanBuild 0.14.9
PortalStations 1.0.9
QuickStack-Store-Sort-Trash-Restock 1.4.7
QuickTeleport 1.0.0
RecyclePlus 1.2.6
ReliableBlock 1.0.0
RepairStation 1.0.4
RocktheBoat 1.0.5
RRRCore 3.1.5
SearsCatalog 1.4.0
Seasonality 3.2.2
SeasonalTweaks 1.0.9
ServerDevcommands 1.75
ServerSideMap 1.3.10.0
ShowWeight 0.0.1
SNEAKer 1.1.3
SpawnThat! 1.2.9
SteadyRegeneration 1.0.2
TorchesAreFires 1.0.4
TradersExtended 1.1.1
UsefulTrophies 1.0.7
ValheimCuisine 2.0.6
ValheimFortress 0.20.4
Veinmine 1.2.10
VikingsDoSwim 1.3.2
WackysDatabase 2.2.5
Warfare 1.6.6
WarfareFireAndIce 1.1.5
WeaponAdditions 1.1.7
WhiteMarble 1.2.0
WieldEquipmentWhileSwimming 1.0.8

I ran the game once without AAAcrafting and SortCraft since both those mods use search bars and no luck.

**Comment by shudnal** [comment]
If you have anything related to any mod in traders list that's first one you should check.

**Comment by shudnal** [comment]
MagicPlugin
MonsterLabZ
Monstrum
PortalStations
RecyclePlus

Maybe some config from WackysDatabase.
That's what caught my sight.

I use Warfare, ValheimCuisine, OdinArchitect and EpicLoot myself. All of them works fine.

I'll check the list later.

**Comment by Bumbletr0n** [comment]
I figured it out. It's not a mod. 
It's the combination of both these config settings that disable the search bar functionality for the Buy column. 
![image](https://github.com/shudnal/TradersExtended/assets/134341663/aed83e7b-6dbe-4182-9516-a3546862fff2)

When **Trader use coins** and **Traders use flexible pricing** are both set to _false_

**Comment by shudnal** [comment]
Ha that's a bummer. Got it fixed thanks.

**Comment by shudnal** [comment]
The fixed version will be soon after I finish with EpicLoot coins.

**Comment by shudnal** [comment]
Pls check 1.1.2. Filter, greyed items and EpicLoot all of that should be fixed.
