### ISSUE TITLE
Trader's coins do not increase when buying items.

### ISSUE THREAD

**Issue by Mofker** [shudnal/TradersExtended#4]
Trader's coins will only decrease when selling items to them. Buying something from them will not increase the amount of coins they have.

**Comment by shudnal** [comment]
It's related to some other mod most likely altering inventory one.

**Comment by shudnal** [comment]
If you find what mod is an issue I can try to provide compatibility

**Comment by Mofker** [comment]
I booted the game up with only TradersExtended and I still have the same issue.
![image](https://github.com/shudnal/TradersExtended/assets/38079264/03a620be-838d-4594-9249-0983b3317639)
![image](https://github.com/shudnal/TradersExtended/assets/38079264/5b5edf3c-c839-417d-95d8-104c2bdafa02)
Purchasing something from Haldor will remove money from my inventory but not add it to his.

**Comment by shudnal** [comment]
What config settings do you use? You can make screenshot of configuration manager window

**Comment by shudnal** [comment]
I've managed to reproduce. Will be fixed in the next version.

**Comment by shudnal** [comment]
Fixed in 1.1.3
