### ISSUE TITLE
No new items in shop

### ISSUE THREAD

**Issue by Z1Zittel** [shudnal/TradersExtended#5]
Hello, I downloaded this mod to play on my world that ive been playing on for the past 8 months. When I go to Haldor he never has any new times in his shop. I have tried to disable the sell-only discovered items and that did not work. I also tried a new character to the world and picked up items that didn't work either. it does pop up with the percentages at the top so the mod is downloaded but all I can buy is the items he originally had.

**Comment by shudnal** [comment]
The mod is only a framework giving you possibility to add any item you need to buy/sell list to specific trader.

**Comment by shudnal** [comment]
Info on how to add items is in description.
There are couple of users list in nexus posts
https://www.nexusmods.com/valheim/mods/2509?tab=posts
And some custom config
https://www.nexusmods.com/valheim/mods/2564
and there are vCommerce configs
https://www.nexusmods.com/valheim/mods/2668
