### ISSUE TITLE
Traders Extended 1.2.1 doesn't load

### ISSUE THREAD

**Issue by ncottrill** [shudnal/TradersExtended#6]
When I upgraded our server and players to Traders Extended 1.2.1 (replacing 1.1.6), it does not load. When we connect to the server, we only see the default trader in game. 

Fortunately, when I reverted the server and players back to Traders Extended 1.1.6, everything worked just fine. The proper Traders Extended NPC shows up with all the expected quests, sales, etc.

**Comment by shudnal** [comment]
Fixed in 1.2.2
