### ISSUE TITLE
Loads for BepinEX 5.4.23.1 but Haldor still shows vanilla

### ISSUE THREAD

**Issue by kwikmr2** [shudnal/TradersExtended#9]
I am using the macOS Steam Valheim client. All of my plugins work using the following method:
https://www.reddit.com/r/valheim/comments/1dcko3i/guide_running_mods_on_macos/

The exception is TradersExtended and Configuration Manager...the later is not really an issue.

`[Message:   BepInEx] BepInEx 5.4.23.1 - Valheim (6/11/2024 9:33:03 AM)
[Info   :   BepInEx] Running under Unity vUnknown (post-2017)
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, iOS
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.1]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Info   :   BepInEx] Detected Unity version: v2022.3.17f1
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 9 plugins to load
[Info   :   BepInEx] Loading [PlantEasily 1.8.1]
[Info   :   BepInEx] Loading [PlantEverything 1.18.1]
[Info   :   BepInEx] Loading [WieldEquipmentWhileSwimming 1.0.9]
[Info   :   BepInEx] Loading [Configuration Manager 18.3]
[Info   :   BepInEx] Loading [Valheim Plus 0.9.13.1]
...
[Info   :Valheim Plus] ValheimPlus done loading.
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[Info   :   BepInEx] Loading [Build Camera 1.6.1]
[Info   :   BepInEx] Loading [Traders Extended 1.2.5]
[Info   :   BepInEx] Loading [Trash Items Mod 1.2.8]
[Info   :Trash Items Mod] TrashItems Loaded!
[Message:   BepInEx] Chainloader startup complete`

**Comment by shudnal** [comment]
The text you added is useless. I can't test it on Mac so without at least error text I can't help at all.

**Comment by shudnal** [comment]
And Configuration Manager version 18.3 is not mine but official one.

**Comment by shudnal** [comment]
Also suggested BepInEx v5.4.23.1 is not preconfigured Valheim version but official one and I have no idea what compatibility issues it could cause.
